import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  entry: [
    // Acceptance CLI entry
    'acceptance/pipeline.ts',

    // Build scripts (JS scripts not auto-discovered)
    'scripts/check-migration-sync.ts',

    // Test support
    'generated-acceptance-tests/helpers.ts',
    'generated-acceptance-tests/globals.d.ts',

    // Stryker vitest config (non-standard name, not auto-discovered)
    'vitest.config.stryker.ts',

    // Claude Code hooks/memory
    '.claude/hooks/*.ts',
    '.claude/memory/*.ts',
    '.claude/types/*.d.ts',

    // Galaxy generator tool
    'tools/**/*.ts',
  ],

  project: [
    'src/**/*.ts',
    'acceptance/**/*.ts',
    'scripts/**/*.{ts,js}',
    '.claude/**/*.ts',
    'generated-acceptance-tests/**/*.ts',
    'tools/**/*.ts',
  ],

  ignore: [
    // Auto-generated by acceptance pipeline
    'generated-acceptance-tests/**/*.spec.ts',
    // Symlink for Hugo's TailwindCSS @source directive — not real source
    'hugo/worker-templates/**',
  ],

  ignoreExportsUsedInFile: true,

  ignoreDependencies: [
    // Loaded by prettier at runtime
    'prettier-plugin-go-template',
    'prettier-plugin-tailwindcss',
    // CLI tools invoked via npx
    '@tktco/node-actionlint',
    '@sentry/cli',
    // Virtual module provided by @cloudflare/vitest-pool-workers
    'cloudflare',
    // Transitive dep of eslint, imported in eslint.config.mjs
    '@eslint/js',
    // JSDoc type reference in stryker.config.mjs (transitive of @stryker-mutator/core)
    '@stryker-mutator/api',
    // Used by tools/galaxy-generator (eslint config)
    'eslint-plugin-prettier',
  ],

  ignoreBinaries: [
    // Installed in hugo/ subdirectory, not in root package.json
    'hugo',
  ],
};

export default config;
