import type { KnipConfig } from 'knip';

const config: KnipConfig = {
  entry: [
    // Acceptance CLI entry
    'acceptance/pipeline.ts',

    // Build scripts (JS scripts not auto-discovered)
    'scripts/check-migration-sync.ts',

    // Test support
    'generated-acceptance-tests/helpers.ts',
    'generated-acceptance-tests/globals.d.ts',

    // Claude Code hooks/memory
    '.claude/hooks/*.ts',
    '.claude/memory/*.ts',
    '.claude/types/*.d.ts',
  ],

  project: [
    'src/**/*.ts',
    'acceptance/**/*.ts',
    'scripts/**/*.{ts,js}',
    '.claude/**/*.ts',
    'generated-acceptance-tests/**/*.ts',
  ],

  ignore: [
    // Auto-generated by acceptance pipeline
    'generated-acceptance-tests/**/*.spec.ts',
  ],

  ignoreDependencies: [
    // Loaded by prettier at runtime
    'prettier-plugin-go-template',
    'prettier-plugin-tailwindcss',
    // CLI tool invoked via npx
    '@tktco/node-actionlint',
    // Virtual module provided by @cloudflare/vitest-pool-workers
    'cloudflare',
    // Transitive dep of eslint, imported in eslint.config.mjs
    '@eslint/js',
  ],

  ignoreBinaries: [
    // Installed in hugo/ subdirectory, not in root package.json
    'hugo',
  ],
};

export default config;
