const ESCAPE_MAP: Record<string, string> = {
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#x27;',
};

const ESCAPE_REGEX = /[&<>"']/g;

/**
 * Escapes HTML special characters to prevent XSS attacks.
 *
 * Replaces `& < > " '` with their corresponding HTML entities.
 *
 * @param str - The string to escape
 * @returns The escaped string safe for HTML insertion
 */
export function escapeHtml(str: string): string {
  return str.replace(
    ESCAPE_REGEX,
    /**
     * Defensive fallback: the regex `/[&<>"']/g` only matches characters
     * present as keys in ESCAPE_MAP, so `ESCAPE_MAP[char]` always resolves.
     * The `?? char` satisfies TypeScript's `noUncheckedIndexedAccess` and
     * guards against future regex/map divergence.
     */
    /* istanbul ignore next -- guaranteed by regex constraint */
    (char) => ESCAPE_MAP[char] ?? char
  );
}

/** Symbol used to identify SafeHtml instances without instanceof checks. */
const SAFE_HTML_BRAND = Symbol('SafeHtml');

/** Wrapper for pre-escaped HTML that should not be double-escaped by the `html` tag. */
interface SafeHtml {
  readonly [SAFE_HTML_BRAND]: true;
  readonly value: string;
}

/**
 * Marks an HTML string as safe (pre-escaped) so the `html` tagged template
 * will not escape it again.
 *
 * Only use this for HTML generated by other trusted template functions.
 *
 * @param value - The pre-escaped HTML string
 * @returns A SafeHtml wrapper
 */
export function safe(value: string): SafeHtml {
  return { [SAFE_HTML_BRAND]: true, value };
}

/**
 * Checks whether a value is a SafeHtml wrapper.
 *
 * @param value - The value to check
 * @returns True if the value is a SafeHtml instance
 */
function isSafeHtml(value: unknown): value is SafeHtml {
  return typeof value === 'object' && value !== null && SAFE_HTML_BRAND in value;
}

/**
 * Tagged template literal that auto-escapes interpolated values.
 *
 * Static template parts are left as-is (they are trusted developer markup).
 * Interpolated values are escaped via {@link escapeHtml} to prevent XSS,
 * unless wrapped with {@link safe} to indicate they are pre-escaped HTML.
 *
 * @param strings - The static template parts
 * @param values - The interpolated values to escape
 * @returns The assembled HTML string with escaped interpolations
 */
export function html(strings: TemplateStringsArray, ...values: unknown[]): string {
  let result = '';
  for (let i = 0; i < strings.length; i++) {
    result += strings[i];
    if (i < values.length) {
      const val = values[i];
      result += isSafeHtml(val) ? val.value : escapeHtml(String(val));
    }
  }
  return result;
}
