// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US01-check-health-status.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";

describe("US01-check-health-status", () => {

// Service reports healthy status.
// Source: specs/acceptance-specs/US01-check-health-status.txt:2
it("Service reports healthy status.", async () => {
  // GIVEN the service is running.
  // WHEN the user requests the health endpoint.
  const res = await SELF.fetch(new Request("https://example.com/api/health"));
  // THEN the response has status 200.
  expect(res.status).toBe(200);
  // THEN the response body shows status ok.
  const body = await res.json() as { status: string };
  expect(body.status).toBe("ok");
});

}); // end describe
