// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US02-api-not-found.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";

import { extractSessionCookie, get, getAuthForm, post, signInAs, submitAuthForm } from "./helpers";

describe("US02-api-not-found", () => {

// API returns structured error for unknown routes.
// Source: specs/acceptance-specs/US02-api-not-found.txt:2
it("API returns structured error for unknown routes.", async () => {
  // GIVEN the service is running.
  // WHEN the user requests an unknown API endpoint.
  const res = await SELF.fetch(new Request("https://example.com/api/nonexistent"));
  // THEN the response has status 404.
  expect(res.status).toBe(404);
  // THEN the response body shows an error message.
  const body = await res.json() as { error: { code: string; message: string } };
  expect(body.error.code).toBe("not_found");
  expect(body.error.message).toBe("Not found");
});

}); // end describe
