// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US03-register-account.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";
import { getAuthForm, submitAuthForm } from "./helpers";

describe("US03-register-account", () => {

// A new visitor can register an account.
// Source: specs/acceptance-specs/US03-register-account.txt:2
it("A new visitor can register an account.", async () => {
  // GIVEN a new visitor is on the registration page.
  const { csrfToken } = await getAuthForm('/auth/sign-up');
  // WHEN they submit a valid email address and a strong password.
  const res = await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789' },
    csrfToken,
    undefined,
    '198.51.100.1',
  );
  // THEN their account is created.
  // THEN they are redirected to the sign-in page.
  expect(res.status).toBe(303);
  // THEN the sign-in page acknowledges that registration was successful.
  expect(res.headers.get('Location')).toBe('/auth/sign-in?registered=true');
});

// Registering with an email already in use silently redirects to sign-in.
// Source: specs/acceptance-specs/US03-register-account.txt:11
it("Registering with an email already in use silently redirects to sign-in.", async () => {
  // GIVEN an account already exists with a given email address.
  const { csrfToken: csrf1 } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789' },
    csrf1,
    undefined,
    '198.51.100.2',
  );
  // WHEN a visitor submits the registration form with that same email address.
  const { csrfToken: csrf2 } = await getAuthForm('/auth/sign-up');
  const res = await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'AnotherStrongPass!456' },
    csrf2,
    undefined,
    '198.51.100.2',
  );
  // THEN they are redirected to the sign-in page.
  expect(res.status).toBe(303);
  // THEN the page gives no indication that the email address was already registered.
  expect(res.headers.get('Location')).toBe('/auth/sign-in?registered=true');
});

// A password shorter than 12 characters is rejected.
// Source: specs/acceptance-specs/US03-register-account.txt:19
it("A password shorter than 12 characters is rejected.", async () => {
  // GIVEN a new visitor is on the registration page.
  const { csrfToken } = await getAuthForm('/auth/sign-up');
  // WHEN they submit a valid email address and a password shorter than 12 characters.
  const res = await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'short' },
    csrfToken,
    undefined,
    '198.51.100.3',
  );
  // THEN they remain on the registration page.
  expect(res.status).toBe(200);
  // THEN they see an error explaining the minimum password length requirement.
  const body = await res.text();
  expect(body).toContain('Password must be at least 12 characters');
});

// A commonly used password is rejected.
// Source: specs/acceptance-specs/US03-register-account.txt:27
it("A commonly used password is rejected.", async () => {
  // GIVEN a new visitor is on the registration page.
  const { csrfToken } = await getAuthForm('/auth/sign-up');
  // WHEN they submit a valid email address and a commonly used password.
  // 'password1234' is 12 characters and is in the OWASP common-passwords list.
  const res = await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'password1234' },
    csrfToken,
    undefined,
    '198.51.100.4',
  );
  // THEN they remain on the registration page.
  expect(res.status).toBe(200);
  // THEN they see an error explaining that the password is too common.
  const body = await res.text();
  expect(body).toContain('Password is too common. Please choose a different password.');
});

// Registration is blocked after too many attempts.
// Source: specs/acceptance-specs/US03-register-account.txt:35
it("Registration is blocked after too many attempts.", async () => {
  // GIVEN a visitor has exceeded the allowed number of registration attempts.
  // Exhaust the rate limit: 5 failed attempts (weak password → weak_password result →
  // increments the Durable Object counter) on a unique IP.
  // Note: password_too_common returns early without incrementing; weak_password does increment.
  const rateLimitIp = '198.51.100.5';
  for (let i = 0; i < 5; i++) {
    const { csrfToken } = await getAuthForm('/auth/sign-up');
    await submitAuthForm(
      '/auth/sign-up',
      { email: `attempt${i.toString()}@example.com`, password: 'short' },
      csrfToken,
      undefined,
      rateLimitIp,
    );
  }
  // WHEN they attempt to register again.
  const { csrfToken } = await getAuthForm('/auth/sign-up');
  const res = await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'short' },
    csrfToken,
    undefined,
    rateLimitIp,
  );
  // THEN they are told to wait before trying again.
  expect(res.status).toBe(429);
});

}); // end describe
