// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US04-sign-in.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";
import { getAuthForm, submitAuthForm, extractSessionCookie } from "./helpers";

describe("US04-sign-in", () => {

// A registered user can sign in.
// Source: specs/acceptance-specs/US04-sign-in.txt:2
it("A registered user can sign in.", async () => {
  // GIVEN a registered user is on the sign-in page.
  // First register the user.
  const { csrfToken: regCsrf } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789' },
    regCsrf,
    undefined,
    '198.51.100.10',
  );
  const { csrfToken: signInCsrf } = await getAuthForm('/auth/sign-in');
  // WHEN they submit their email address and correct password.
  const res = await submitAuthForm(
    '/auth/sign-in',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789' },
    signInCsrf,
    undefined,
    '198.51.100.10',
  );
  // THEN they are signed in and redirected to the application.
  expect(res.status).toBe(303);
  const sessionCookie = extractSessionCookie(res);
  expect(sessionCookie).not.toBe('');
});

// An incorrect password shows a generic error.
// Source: specs/acceptance-specs/US04-sign-in.txt:9
it("An incorrect password shows a generic error.", async () => {
  // GIVEN a registered user is on the sign-in page.
  const { csrfToken: regCsrf } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789' },
    regCsrf,
    undefined,
    '198.51.100.11',
  );
  const { csrfToken: signInCsrf } = await getAuthForm('/auth/sign-in');
  // WHEN they submit their email address with an incorrect password.
  const res = await submitAuthForm(
    '/auth/sign-in',
    { email: 'alice@example.com', password: 'WrongPassword123!' },
    signInCsrf,
    undefined,
    '198.51.100.11',
  );
  // THEN they remain on the sign-in page.
  expect(res.status).toBe(200);
  // THEN they see a generic error that does not reveal whether the email exists.
  const body = await res.text();
  expect(body).toContain('Invalid email or password');
});

// An unregistered email shows the same generic error.
// Source: specs/acceptance-specs/US04-sign-in.txt:17
it("An unregistered email shows the same generic error.", async () => {
  // GIVEN a visitor is on the sign-in page.
  const { csrfToken } = await getAuthForm('/auth/sign-in');
  // WHEN they submit an email address with no registered account.
  const res = await submitAuthForm(
    '/auth/sign-in',
    { email: 'nobody@example.com', password: 'SomePassword#789' },
    csrfToken,
    undefined,
    '198.51.100.12',
  );
  // THEN they remain on the sign-in page.
  expect(res.status).toBe(200);
  // THEN they see the same generic error as for an incorrect password.
  const body = await res.text();
  expect(body).toContain('Invalid email or password');
});

// Sign-in is blocked after too many failed attempts.
// Source: specs/acceptance-specs/US04-sign-in.txt:25
it.todo("Sign-in is blocked after too many failed attempts.");

// The original destination is preserved through sign-in.
// Source: specs/acceptance-specs/US04-sign-in.txt:32
it("The original destination is preserved through sign-in.", async () => {
  // GIVEN an unauthenticated visitor attempts to access a protected page.
  const accessRes = await SELF.fetch(
    new Request('https://example.com/app/', { redirect: 'manual' }),
  );
  expect(accessRes.status).toBe(302);
  const signInUrl = accessRes.headers.get('Location') ?? '';
  const redirectTo = new URL(signInUrl, 'https://example.com').searchParams.get('redirectTo') ?? '/';
  // WHEN they are redirected to the sign-in page and sign in successfully.
  // Register first, then sign in including the redirectTo destination.
  const { csrfToken: regCsrf } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789' },
    regCsrf,
    undefined,
    '198.51.100.14',
  );
  const { csrfToken: signInCsrf } = await getAuthForm('/auth/sign-in');
  const signInRes = await submitAuthForm(
    '/auth/sign-in',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789', redirectTo },
    signInCsrf,
    undefined,
    '198.51.100.14',
  );
  // THEN they are sent to the page they originally requested.
  expect(signInRes.status).toBe(303);
  expect(signInRes.headers.get('Location')).toBe('/app/');
});

}); // end describe
