// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US04-sign-in.txt (rate limit scenario, isolated for DO storage compatibility)

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";
import { getAuthForm, submitAuthForm } from "./helpers";

describe("US04-sign-in-rate-limit", () => {

// Sign-in is blocked after too many failed attempts.
// Source: specs/acceptance-specs/US04-sign-in.txt:25
it("Sign-in is blocked after too many failed attempts.", { timeout: 30_000 }, async () => {
  // GIVEN a visitor has exceeded the allowed number of sign-in attempts.
  const ip = '198.51.100.99';
  const { csrfToken: regCsrf } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'ratelimit@example.com', password: 'SuperSecure#Pass789', password_confirm: 'SuperSecure#Pass789' },
    regCsrf,
    undefined,
    ip,
  );
  // Exhaust 5 allowed attempts with wrong passwords.
  for (let i = 0; i < 5; i++) {
    const { csrfToken } = await getAuthForm('/auth/sign-in');
    const failRes = await submitAuthForm(
      '/auth/sign-in',
      { email: 'ratelimit@example.com', password: 'WrongPassword!' + String(i) },
      csrfToken,
      undefined,
      ip,
    );
    await failRes.text();
  }
  // WHEN they attempt to sign in again.
  const { csrfToken: finalCsrf } = await getAuthForm('/auth/sign-in');
  const res = await submitAuthForm(
    '/auth/sign-in',
    { email: 'ratelimit@example.com', password: 'SuperSecure#Pass789' },
    finalCsrf,
    undefined,
    ip,
  );
  // THEN they are told to wait before trying again.
  expect(res.status).toBe(429);
  const body = await res.text();
  expect(body).toContain('Too Many Requests');
});

}); // end describe
