// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US05-sign-out.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";

import { extractSessionCookie, get, getAuthForm, post, signInAs, submitAuthForm } from "./helpers";

describe("US05-sign-out", () => {

// A signed-in user can sign out.
// Source: specs/acceptance-specs/US05-sign-out.txt:2
it("A signed-in user can sign out.", async () => {
  // GIVEN a signed-in user.
  // Register then sign in to obtain a session cookie.
  const { csrfToken: regCsrf } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789', password_confirm: 'SuperSecure#Pass789' },
    regCsrf,
    undefined,
    '198.51.100.20',
  );
  const sessionCookie = await signInAs('alice@example.com', 'SuperSecure#Pass789', '198.51.100.20');
  // WHEN they sign out.
  // Get a fresh CSRF token then POST to sign-out with the session cookie.
  const { csrfToken: signOutCsrf } = await getAuthForm('/auth/sign-in');
  const res = await submitAuthForm('/auth/sign-out', {}, signOutCsrf, sessionCookie, '198.51.100.20');
  // THEN their session ends.
  // THEN they are redirected to the sign-in page.
  expect(res.status).toBe(303);
  expect(res.headers.get('Location')).toBe('/auth/sign-in');
});

// After signing out, protected pages are inaccessible.
// Source: specs/acceptance-specs/US05-sign-out.txt:10
it("After signing out, protected pages are inaccessible.", async () => {
  // GIVEN a user who has just signed out.
  const { csrfToken: regCsrf } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789', password_confirm: 'SuperSecure#Pass789' },
    regCsrf,
    undefined,
    '198.51.100.21',
  );
  const sessionCookie = await signInAs('alice@example.com', 'SuperSecure#Pass789', '198.51.100.21');
  // Sign out to invalidate the session.
  const { csrfToken: signOutCsrf } = await getAuthForm('/auth/sign-in');
  await submitAuthForm('/auth/sign-out', {}, signOutCsrf, sessionCookie, '198.51.100.21');
  // WHEN they attempt to access a protected page.
  // Use the old session cookie — it should no longer be accepted.
  const res = await SELF.fetch(
    new Request('https://example.com/app/', {
      headers: { Cookie: sessionCookie },
      redirect: 'manual',
    }),
  );
  // THEN they are redirected to the sign-in page.
  expect(res.status).toBe(302);
  expect(res.headers.get('Location')).toMatch(/^\/auth\/sign-in/);
});

}); // end describe
