// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US06-access-protected-pages.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";

import { extractSessionCookie, get, getAuthForm, post, signInAs, submitAuthForm } from "./helpers";

describe("US06-access-protected-pages", () => {

// An unauthenticated visitor is redirected from a protected page.
// Source: specs/acceptance-specs/US06-access-protected-pages.txt:2
it("An unauthenticated visitor is redirected from a protected page.", async () => {
  // GIVEN a visitor with no active session.
  // WHEN they attempt to access a protected page.
  const res = await SELF.fetch(
    new Request('https://example.com/app/', { redirect: 'manual' }),
  );
  // THEN they are redirected to the sign-in page.
  expect(res.status).toBe(302);
  // THEN the sign-in page retains the address of the page they originally requested.
  const location = res.headers.get('Location') ?? '';
  expect(location).toMatch(/^\/auth\/sign-in\?redirectTo=/);
  expect(location).toContain(encodeURIComponent('/app/'));
});

// An authenticated user can access protected pages.
// Source: specs/acceptance-specs/US06-access-protected-pages.txt:10
it("An authenticated user can access protected pages.", async () => {
  // GIVEN a signed-in user.
  const { csrfToken: regCsrf } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789' },
    regCsrf,
    undefined,
    '198.51.100.31',
  );
  const sessionCookie = await signInAs('alice@example.com', 'SuperSecure#Pass789', '198.51.100.31');
  // WHEN they access a protected page.
  const res = await SELF.fetch(
    new Request('https://example.com/app/', {
      headers: { Cookie: sessionCookie },
      redirect: 'manual',
    }),
  );
  // THEN they are served the protected content (any non-redirect response).
  expect(res.status).not.toBe(302);
});

// An expired session is treated as no session.
// Source: specs/acceptance-specs/US06-access-protected-pages.txt:17
it("An expired session is treated as no session.", async () => {
  // GIVEN a user whose session has expired.
  // Register and sign in to obtain a session cookie.
  const { csrfToken: regCsrf } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789' },
    regCsrf,
    undefined,
    '198.51.100.32',
  );
  const sessionCookie = await signInAs('alice@example.com', 'SuperSecure#Pass789', '198.51.100.32');
  // Simulate session expiry by deleting all sessions from D1.
  // better-auth immediately deletes expired sessions on detection, so the
  // observable behaviour is identical: the session no longer exists in D1.
  await env.DB.exec("DELETE FROM session");
  // WHEN they attempt to access a protected page.
  const res = await SELF.fetch(
    new Request('https://example.com/app/', {
      headers: { Cookie: sessionCookie },
      redirect: 'manual',
    }),
  );
  // THEN they are redirected to the sign-in page.
  expect(res.status).toBe(302);
  expect(res.headers.get('Location')).toMatch(/^\/auth\/sign-in/);
});

}); // end describe
