// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US07-workspace-provisioning.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";

import { extractSessionCookie, get, getAuthForm, post, signInAs, submitAuthForm } from "./helpers";

describe("US07-workspace-provisioning", () => {

// New user signup automatically provisions workspace with seed data.
// Source: specs/acceptance-specs/US07-workspace-provisioning.txt:2
it("New user signup automatically provisions workspace with seed data.", async () => {
  // GIVEN a new user signs up with a valid email and password.
  const { csrfToken } = await getAuthForm('/auth/sign-up');

  // WHEN registration completes successfully.
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789', password_confirm: 'SuperSecure#Pass789' },
    csrfToken,
    undefined,
    '198.51.100.71',
  );
  const sessionCookie = await signInAs('alice@example.com', 'SuperSecure#Pass789', '198.51.100.71');

  // THEN a workspace is created for the user.
  const workspaceRows = await env.DB.prepare('SELECT id FROM workspace').all();
  expect(workspaceRows.results).toHaveLength(1);

  // THEN a human actor is created linked to the user account.
  const actorRows = await env.DB.prepare("SELECT id, type FROM actor WHERE type = 'human'").all();
  expect(actorRows.results).toHaveLength(1);

  // THEN three default areas are created: Work, Personal, and Admin.
  const areasRes = await SELF.fetch(
    new Request('https://example.com/api/v1/areas', {
      headers: { Cookie: sessionCookie },
    }),
  );
  expect(areasRes.status).toBe(200);
  const areas = await areasRes.json() as Array<{ id: string; name: string; status: string }>;
  expect(areas).toHaveLength(3);
  const areaNames = areas.map((a) => a.name).sort();
  expect(areaNames).toEqual(['Admin', 'Personal', 'Work']);

  // THEN five default contexts are created: computer, calls, home, errands, and office.
  const contextsRes = await SELF.fetch(
    new Request('https://example.com/api/v1/contexts', {
      headers: { Cookie: sessionCookie },
    }),
  );
  expect(contextsRes.status).toBe(200);
  const contexts = await contextsRes.json() as Array<{ id: string; name: string }>;
  expect(contexts).toHaveLength(5);
  const contextNames = contexts.map((c) => c.name).sort();
  expect(contextNames).toEqual(['calls', 'computer', 'errands', 'home', 'office']);
});

// Provisioned workspace exposes seeded areas via the API.
// Source: specs/acceptance-specs/US07-workspace-provisioning.txt:12
it("Provisioned workspace exposes seeded areas via the API.", async () => {
  // GIVEN a user has a provisioned workspace with seed data.
  const { csrfToken } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'bob@example.com', password: 'SuperSecure#Pass789', password_confirm: 'SuperSecure#Pass789' },
    csrfToken,
    undefined,
    '198.51.100.72',
  );
  const sessionCookie = await signInAs('bob@example.com', 'SuperSecure#Pass789', '198.51.100.72');

  // WHEN the user requests GET /api/v1/areas.
  const res = await SELF.fetch(
    new Request('https://example.com/api/v1/areas', {
      headers: { Cookie: sessionCookie },
    }),
  );

  // THEN the response has status 200.
  expect(res.status).toBe(200);

  // THEN the response body contains exactly three areas.
  const areas = await res.json() as Array<{ id: string; name: string; status: string }>;
  expect(areas).toHaveLength(3);
});

// Provisioned workspace exposes seeded contexts via the API.
// Source: specs/acceptance-specs/US07-workspace-provisioning.txt:20
it("Provisioned workspace exposes seeded contexts via the API.", async () => {
  // GIVEN a user has a provisioned workspace with seed data.
  const { csrfToken } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'charlie@example.com', password: 'SuperSecure#Pass789', password_confirm: 'SuperSecure#Pass789' },
    csrfToken,
    undefined,
    '198.51.100.73',
  );
  const sessionCookie = await signInAs('charlie@example.com', 'SuperSecure#Pass789', '198.51.100.73');

  // WHEN the user requests GET /api/v1/contexts.
  const res = await SELF.fetch(
    new Request('https://example.com/api/v1/contexts', {
      headers: { Cookie: sessionCookie },
    }),
  );

  // THEN the response has status 200.
  expect(res.status).toBe(200);

  // THEN the response body contains exactly five contexts.
  const contexts = await res.json() as Array<{ id: string; name: string }>;
  expect(contexts).toHaveLength(5);
});

}); // end describe
