// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US08-inbox-capture.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";

import { extractSessionCookie, get, getAuthForm, post, signInAs, submitAuthForm } from "./helpers";

describe("US08-inbox-capture", () => {

// Authenticated user can capture an item to their inbox.
// Source: specs/acceptance-specs/US08-inbox-capture.txt:2
it("Authenticated user can capture an item to their inbox.", async () => {
  // GIVEN the user is authenticated with a provisioned workspace.
  const { csrfToken } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'inbox-capture@example.com', password: 'SuperSecure#Pass789', password_confirm: 'SuperSecure#Pass789' },
    csrfToken,
    undefined,
    '198.51.100.80',
  );
  const sessionCookie = await signInAs('inbox-capture@example.com', 'SuperSecure#Pass789', '198.51.100.80');

  // WHEN the user POSTs to /api/v1/inbox with a non-empty title.
  const res = await SELF.fetch(
    new Request('https://example.com/api/v1/inbox', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Cookie: sessionCookie,
      },
      body: JSON.stringify({ title: 'Buy groceries' }),
    }),
  );

  // THEN the response has status 201.
  expect(res.status).toBe(201);

  // THEN the response body contains the created inbox item with status inbox.
  const body = await res.json() as { id: string; title: string; status: string };
  expect(body.title).toBe('Buy groceries');
  expect(body.status).toBe('inbox');
  expect(body.id).toBeDefined();

  // THEN an audit event is recorded for the capture.
  const auditRows = await env.DB.prepare(
    "SELECT * FROM audit_event WHERE entity_type = 'inbox_item' AND event_type = 'inbox_item.captured'"
  ).all();
  expect(auditRows.results.length).toBeGreaterThanOrEqual(1);
});

// Submitting an empty title is rejected with a descriptive error.
// Source: specs/acceptance-specs/US08-inbox-capture.txt:11
it("Submitting an empty title is rejected with a descriptive error.", async () => {
  // GIVEN the user is authenticated with a provisioned workspace.
  const { csrfToken } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'inbox-empty@example.com', password: 'SuperSecure#Pass789', password_confirm: 'SuperSecure#Pass789' },
    csrfToken,
    undefined,
    '198.51.100.81',
  );
  const sessionCookie = await signInAs('inbox-empty@example.com', 'SuperSecure#Pass789', '198.51.100.81');

  // WHEN the user POSTs to /api/v1/inbox with an empty title.
  const res = await SELF.fetch(
    new Request('https://example.com/api/v1/inbox', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Cookie: sessionCookie,
      },
      body: JSON.stringify({ title: '' }),
    }),
  );

  // THEN the response has status 400.
  expect(res.status).toBe(400);

  // THEN the response body contains a descriptive error message.
  const body = await res.json() as { error: string };
  expect(body.error).toBeDefined();
});

// Authenticated user can list their inbox items.
// Source: specs/acceptance-specs/US08-inbox-capture.txt:19
it("Authenticated user can list their inbox items.", async () => {
  // GIVEN the user is authenticated with a provisioned workspace.
  const { csrfToken } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'inbox-list@example.com', password: 'SuperSecure#Pass789', password_confirm: 'SuperSecure#Pass789' },
    csrfToken,
    undefined,
    '198.51.100.82',
  );
  const sessionCookie = await signInAs('inbox-list@example.com', 'SuperSecure#Pass789', '198.51.100.82');

  // GIVEN the user has captured at least one item to their inbox.
  await SELF.fetch(
    new Request('https://example.com/api/v1/inbox', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Cookie: sessionCookie,
      },
      body: JSON.stringify({ title: 'First task' }),
    }),
  );

  // WHEN the user requests GET /api/v1/inbox.
  const res = await SELF.fetch(
    new Request('https://example.com/api/v1/inbox', {
      headers: { Cookie: sessionCookie },
    }),
  );

  // THEN the response has status 200.
  expect(res.status).toBe(200);

  // THEN the response body contains only inbox items with status inbox.
  const items = await res.json() as Array<{ id: string; title: string; status: string }>;
  expect(items.length).toBeGreaterThanOrEqual(1);
  for (const item of items) {
    expect(item.status).toBe('inbox');
  }
});

}); // end describe
