// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US09-clarify-inbox-item.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";

import { extractSessionCookie, get, getAuthForm, post, signInAs, submitAuthForm } from "./helpers";

describe("US09-clarify-inbox-item", () => {

// Clarifying an inbox item creates an action and marks the item clarified.
// Source: specs/acceptance-specs/US09-clarify-inbox-item.txt:2
it("Clarifying an inbox item creates an action and marks the item clarified.", async () => {
  // GIVEN the user has an inbox item in inbox status.
  const sessionCookie = await setupUser('clarify-ok@example.com', '198.51.100.90');
  const inboxItemId = await captureInboxItem(sessionCookie, 'Write blog post');
  const areaId = await getFirstAreaId(sessionCookie);
  const contextId = await getFirstContextId(sessionCookie);

  // WHEN the user POSTs to /api/v1/inbox/:id/clarify with a title, areaId, and contextId.
  const res = await SELF.fetch(
    new Request(`https://example.com/api/v1/inbox/${inboxItemId}/clarify`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Cookie: sessionCookie },
      body: JSON.stringify({ title: 'Write blog post', areaId, contextId }),
    }),
  );

  // THEN the response has status 200.
  expect(res.status).toBe(200);

  // THEN a new action exists with status ready.
  const action = await res.json() as { id: string; status: string; title: string };
  expect(action.status).toBe('ready');
  expect(action.title).toBe('Write blog post');

  // THEN the inbox item status becomes clarified.
  const inboxRes = await SELF.fetch(
    new Request('https://example.com/api/v1/inbox', { headers: { Cookie: sessionCookie } }),
  );
  const inboxItems = await inboxRes.json() as Array<{ id: string; status: string }>;
  // The clarified item should NOT appear in the inbox list (which filters by status='inbox')
  const found = inboxItems.find((item) => item.id === inboxItemId);
  expect(found).toBeUndefined();

  // THEN audit events are recorded for both the inbox item and the action.
  const auditRows = await env.DB.prepare(
    "SELECT * FROM audit_event WHERE event_type IN ('inbox_item.clarified', 'action.created')"
  ).all();
  expect(auditRows.results.length).toBeGreaterThanOrEqual(2);
});

// Attempting to clarify an already-clarified item is rejected.
// Source: specs/acceptance-specs/US09-clarify-inbox-item.txt:12
it("Attempting to clarify an already-clarified item is rejected.", async () => {
  // GIVEN the user has an inbox item in clarified status.
  const sessionCookie = await setupUser('clarify-dup@example.com', '198.51.100.91');
  const inboxItemId = await captureInboxItem(sessionCookie, 'Already clarified');
  const areaId = await getFirstAreaId(sessionCookie);
  const contextId = await getFirstContextId(sessionCookie);

  // Clarify it first
  await SELF.fetch(
    new Request(`https://example.com/api/v1/inbox/${inboxItemId}/clarify`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Cookie: sessionCookie },
      body: JSON.stringify({ title: 'Already clarified', areaId, contextId }),
    }),
  );

  // WHEN the user POSTs to /api/v1/inbox/:id/clarify again.
  const res = await SELF.fetch(
    new Request(`https://example.com/api/v1/inbox/${inboxItemId}/clarify`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Cookie: sessionCookie },
      body: JSON.stringify({ title: 'Already clarified', areaId, contextId }),
    }),
  );

  // THEN the response has status 409 (already clarified = conflict).
  expect(res.status).toBe(409);

  // THEN the response body describes the invalid status transition.
  const body = await res.json() as { error: { code: string; message: string } };
  expect(body.error.code).toBe('already_clarified');
});

// Clarification with a non-existent or archived area is rejected.
// Source: specs/acceptance-specs/US09-clarify-inbox-item.txt:20
it("Clarification with a non-existent or archived area is rejected.", async () => {
  // GIVEN the user has an inbox item in inbox status.
  const sessionCookie = await setupUser('clarify-bad-area@example.com', '198.51.100.92');
  const inboxItemId = await captureInboxItem(sessionCookie, 'Bad area test');
  const contextId = await getFirstContextId(sessionCookie);

  // WHEN the user POSTs to /api/v1/inbox/:id/clarify with a non-existent or archived areaId.
  const res = await SELF.fetch(
    new Request(`https://example.com/api/v1/inbox/${inboxItemId}/clarify`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Cookie: sessionCookie },
      body: JSON.stringify({ title: 'Bad area test', areaId: 'nonexistent-area-id', contextId }),
    }),
  );

  // THEN the response has status 404 (area not found).
  expect(res.status).toBe(404);

  // THEN the response body describes the invalid area reference.
  const body = await res.json() as { error: { code: string; message: string } };
  expect(body.error.code).toBe('area_not_found_or_archived');
});

// Clarification with a non-existent context is rejected.
// Source: specs/acceptance-specs/US09-clarify-inbox-item.txt:28
it("Clarification with a non-existent context is rejected.", async () => {
  // GIVEN the user has an inbox item in inbox status.
  const sessionCookie = await setupUser('clarify-bad-ctx@example.com', '198.51.100.93');
  const inboxItemId = await captureInboxItem(sessionCookie, 'Bad context test');
  const areaId = await getFirstAreaId(sessionCookie);

  // WHEN the user POSTs to /api/v1/inbox/:id/clarify with a non-existent contextId.
  const res = await SELF.fetch(
    new Request(`https://example.com/api/v1/inbox/${inboxItemId}/clarify`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Cookie: sessionCookie },
      body: JSON.stringify({ title: 'Bad context test', areaId, contextId: 'nonexistent-ctx-id' }),
    }),
  );

  // THEN the response has status 404 (context not found).
  expect(res.status).toBe(404);

  // THEN the response body describes the invalid context reference.
  const body = await res.json() as { error: { code: string; message: string } };
  expect(body.error.code).toBe('context_not_found');
});

}); // end describe
