// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US10-activate-complete-action.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";

import { extractSessionCookie, get, getAuthForm, post, signInAs, submitAuthForm } from "./helpers";

describe("US10-activate-complete-action", () => {

// A ready action can be activated.
// Source: specs/acceptance-specs/US10-activate-complete-action.txt:2
it("A ready action can be activated.", async () => {
  // GIVEN the user has an action in ready status.
  const sessionCookie = await setupUser('activate-ok@example.com', '198.51.100.100');
  const actionId = await createReadyAction(sessionCookie, 'Activate me');

  // WHEN the user POSTs to /api/v1/actions/:id/activate.
  const res = await SELF.fetch(
    new Request(`https://example.com/api/v1/actions/${actionId}/activate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Cookie: sessionCookie },
    }),
  );

  // THEN the response has status 200.
  expect(res.status).toBe(200);

  // THEN the action status becomes active.
  const action = await res.json() as { id: string; status: string };
  expect(action.status).toBe('active');

  // THEN an audit event is recorded for the activation.
  const auditRows = await env.DB.prepare(
    "SELECT * FROM audit_event WHERE event_type = 'action.activated'"
  ).all();
  expect(auditRows.results.length).toBeGreaterThanOrEqual(1);
});

// An active action can be completed.
// Source: specs/acceptance-specs/US10-activate-complete-action.txt:11
it("An active action can be completed.", async () => {
  // GIVEN the user has an action in active status.
  const sessionCookie = await setupUser('complete-ok@example.com', '198.51.100.101');
  const actionId = await createReadyAction(sessionCookie, 'Complete me');

  // Activate it first
  await SELF.fetch(
    new Request(`https://example.com/api/v1/actions/${actionId}/activate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Cookie: sessionCookie },
    }),
  );

  // WHEN the user POSTs to /api/v1/actions/:id/complete.
  const res = await SELF.fetch(
    new Request(`https://example.com/api/v1/actions/${actionId}/complete`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Cookie: sessionCookie },
    }),
  );

  // THEN the response has status 200.
  expect(res.status).toBe(200);

  // THEN the action status becomes done.
  const action = await res.json() as { id: string; status: string };
  expect(action.status).toBe('done');

  // THEN an audit event is recorded for the completion.
  const auditRows = await env.DB.prepare(
    "SELECT * FROM audit_event WHERE event_type = 'action.completed'"
  ).all();
  expect(auditRows.results.length).toBeGreaterThanOrEqual(1);
});

// Attempting to activate a done action is rejected.
// Source: specs/acceptance-specs/US10-activate-complete-action.txt:20
it("Attempting to activate a done action is rejected.", async () => {
  // GIVEN the user has an action in done status.
  const sessionCookie = await setupUser('activate-done@example.com', '198.51.100.102');
  const actionId = await createReadyAction(sessionCookie, 'Already done');

  // Move to active then done
  await SELF.fetch(
    new Request(`https://example.com/api/v1/actions/${actionId}/activate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Cookie: sessionCookie },
    }),
  );
  await SELF.fetch(
    new Request(`https://example.com/api/v1/actions/${actionId}/complete`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Cookie: sessionCookie },
    }),
  );

  // WHEN the user POSTs to /api/v1/actions/:id/activate.
  const res = await SELF.fetch(
    new Request(`https://example.com/api/v1/actions/${actionId}/activate`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Cookie: sessionCookie },
    }),
  );

  // THEN the response has status 409 (invalid status transition = conflict).
  expect(res.status).toBe(409);

  // THEN the response body describes the invalid status transition.
  const body = await res.json() as { error: { code: string; message: string } };
  expect(body.error.code).toBe('invalid_status_transition');
});

// Attempting to complete a ready action without activating it first is rejected.
// Source: specs/acceptance-specs/US10-activate-complete-action.txt:28
it("Attempting to complete a ready action without activating it first is rejected.", async () => {
  // GIVEN the user has an action in ready status.
  const sessionCookie = await setupUser('complete-ready@example.com', '198.51.100.103');
  const actionId = await createReadyAction(sessionCookie, 'Still ready');

  // WHEN the user POSTs to /api/v1/actions/:id/complete directly without activating first.
  const res = await SELF.fetch(
    new Request(`https://example.com/api/v1/actions/${actionId}/complete`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', Cookie: sessionCookie },
    }),
  );

  // THEN the response has status 409 (invalid status transition = conflict).
  expect(res.status).toBe(409);

  // THEN the response body describes the invalid status transition.
  const body = await res.json() as { error: { code: string; message: string } };
  expect(body.error.code).toBe('invalid_status_transition');
});

}); // end describe
