// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US14-authenticated-navbar-swap.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";

describe("US14-authenticated-navbar-swap", () => {

// Authenticated users see a Dashboard link in the navbar.
// Source: specs/acceptance-specs/US14-authenticated-navbar-swap.txt:2
it("Authenticated users see a Dashboard link in the navbar.", async () => {
  // GIVEN an authenticated user on any page.
  // WHEN the page loads.
  // THEN the navbar displays a "Dashboard" link pointing to /dashboard/ instead of Sign In and Sign Up links.

  throw new Error("acceptance test not yet bound");
});

// Unauthenticated visitors see Sign In and Sign Up links in the navbar.
// Source: specs/acceptance-specs/US14-authenticated-navbar-swap.txt:9
it("Unauthenticated visitors see Sign In and Sign Up links in the navbar.", async () => {
  // GIVEN an unauthenticated visitor on any page.
  // WHEN the page loads.
  // THEN the navbar displays "Sign In" and "Sign Up" links.

  throw new Error("acceptance test not yet bound");
});

// The Dashboard link navigates to the dashboard page.
// Source: specs/acceptance-specs/US14-authenticated-navbar-swap.txt:16
it("The Dashboard link navigates to the dashboard page.", async () => {
  // GIVEN an authenticated user viewing the navbar.
  // WHEN they click the "Dashboard" link.
  // THEN the browser navigates to /dashboard/.

  throw new Error("acceptance test not yet bound");
});

}); // end describe
