// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US14-authenticated-navbar-swap.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";

import { extractSessionCookie, get, getAuthForm, post, signInAs, submitAuthForm } from "./helpers";

describe("US14-authenticated-navbar-swap", () => {

// Authenticated users see a Dashboard link in the navbar.
// Source: specs/acceptance-specs/US14-authenticated-navbar-swap.txt:2
it("Authenticated users see a Dashboard link in the navbar.", async () => {
  // GIVEN an authenticated user on any page.
  const { csrfToken: regCsrf } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789', password_confirm: 'SuperSecure#Pass789' },
    regCsrf,
    undefined,
    '198.51.100.1',
  );
  const { csrfToken: signInCsrf } = await getAuthForm('/auth/sign-in');
  const signInRes = await submitAuthForm(
    '/auth/sign-in',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789' },
    signInCsrf,
    undefined,
    '198.51.100.1',
  );

  // WHEN the page loads.
  // The sign-in response sets the auth_status indicator cookie which
  // tells the Alpine.js auth store to display the authenticated navbar.
  const setCookie = signInRes.headers.get('Set-Cookie') ?? '';
  const sessionCookie = extractSessionCookie(signInRes);
  const pageRes = await SELF.fetch(
    new Request('https://example.com/', {
      headers: { Cookie: sessionCookie },
    }),
  );
  const html = await pageRes.text();

  // THEN the navbar displays a "Dashboard" link pointing to /dashboard/
  // instead of Sign In and Sign Up links.
  // The __Host-auth_status=1 indicator cookie drives the Alpine.js swap.
  expect(setCookie).toContain('__Host-auth_status=1');
  expect(html).toContain('Dashboard');
  expect(html).toContain('/dashboard/');
  // The authenticated menu is wired to the Alpine.js auth store via class binding.
  expect(html).toContain(":class=\"{ 'hidden': !$store.auth.isAuthenticated }\"");
});

// Unauthenticated visitors see Sign In and Sign Up links in the navbar.
// Source: specs/acceptance-specs/US14-authenticated-navbar-swap.txt:9
it("Unauthenticated visitors see Sign In and Sign Up links in the navbar.", async () => {
  // GIVEN an unauthenticated visitor on any page.
  // WHEN the page loads.
  const res = await SELF.fetch(
    new Request('https://example.com/'),
  );
  const html = await res.text();

  // THEN the navbar displays "Sign In" and "Sign Up" links.
  expect(html).toContain('Sign In');
  expect(html).toContain('Sign Up');
  // The unauthenticated menu toggles visibility via class binding (visible when no auth_status cookie).
  expect(html).toContain(":class=\"{ 'hidden': $store.auth.isAuthenticated }\"");
  // No auth_status cookie is set for unauthenticated responses.
  const setCookie = res.headers.get('Set-Cookie') ?? '';
  expect(setCookie).not.toContain('__Host-auth_status=1');
});

// The Dashboard link navigates to the dashboard page.
// Source: specs/acceptance-specs/US14-authenticated-navbar-swap.txt:16
it("The Dashboard link navigates to the dashboard page.", async () => {
  // GIVEN an authenticated user viewing the navbar.
  const { csrfToken: regCsrf } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'bob@example.com', password: 'SuperSecure#Pass789', password_confirm: 'SuperSecure#Pass789' },
    regCsrf,
    undefined,
    '198.51.100.2',
  );
  const sessionCookie = await signInAs('bob@example.com', 'SuperSecure#Pass789', '198.51.100.2');

  // WHEN they click the "Dashboard" link.
  const res = await SELF.fetch(
    new Request('https://example.com/dashboard/', {
      headers: { Cookie: sessionCookie },
      redirect: 'manual',
    }),
  );

  // THEN the browser navigates to /dashboard/.
  // The auth guard allows access (no redirect), serving the dashboard page.
  expect(res.status).not.toBe(302);
  const html = await res.text();
  expect(html).toContain('Dashboard');
});

}); // end describe
