// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US15-dashboard-auth-guard.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";

import { getAuthForm, signInAs, submitAuthForm } from './helpers';

describe("US15-dashboard-auth-guard", () => {

// An authenticated user can view the dashboard.
// Source: specs/acceptance-specs/US15-dashboard-auth-guard.txt:2
it("An authenticated user can view the dashboard.", async () => {
  // GIVEN a user who has signed in.
  const { csrfToken: regCsrf } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789' },
    regCsrf,
    undefined,
    '198.51.100.50',
  );
  const sessionCookie = await signInAs('alice@example.com', 'SuperSecure#Pass789', '198.51.100.50');

  // WHEN they navigate to the dashboard page.
  const res = await SELF.fetch(
    new Request('https://example.com/dashboard/', {
      headers: { Cookie: sessionCookie },
      redirect: 'manual',
    }),
  );

  // THEN the dashboard content is displayed.
  expect(res.status).not.toBe(302);
});

// An unauthenticated visitor is redirected from the dashboard to sign-in.
// Source: specs/acceptance-specs/US15-dashboard-auth-guard.txt:9
it("An unauthenticated visitor is redirected from the dashboard to sign-in.", async () => {
  // GIVEN a visitor who has not signed in.
  // WHEN they navigate to the dashboard page.
  const res = await SELF.fetch(
    new Request('https://example.com/dashboard/', { redirect: 'manual' }),
  );

  // THEN they are redirected to the sign-in page.
  expect(res.status).toBe(302);

  // THEN the sign-in page retains the address of the dashboard as the return destination.
  const location = res.headers.get('Location') ?? '';
  expect(location).toMatch(/^\/auth\/sign-in\?redirectTo=/);
  expect(location).toContain(encodeURIComponent('/dashboard/'));
});

// After signing in, the user is returned to the dashboard.
// Source: specs/acceptance-specs/US15-dashboard-auth-guard.txt:17
it("After signing in, the user is returned to the dashboard.", async () => {
  // GIVEN a visitor who was redirected from the dashboard to the sign-in page.
  const accessRes = await SELF.fetch(
    new Request('https://example.com/dashboard/', { redirect: 'manual' }),
  );
  expect(accessRes.status).toBe(302);
  const signInUrl = accessRes.headers.get('Location') ?? '';
  const redirectTo = new URL(signInUrl, 'https://example.com').searchParams.get('redirectTo') ?? '/';

  // WHEN they sign in successfully.
  const { csrfToken: regCsrf } = await getAuthForm('/auth/sign-up');
  await submitAuthForm(
    '/auth/sign-up',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789' },
    regCsrf,
    undefined,
    '198.51.100.51',
  );
  const { csrfToken: signInCsrf } = await getAuthForm('/auth/sign-in');
  const signInRes = await submitAuthForm(
    '/auth/sign-in',
    { email: 'alice@example.com', password: 'SuperSecure#Pass789', redirectTo },
    signInCsrf,
    undefined,
    '198.51.100.51',
  );

  // THEN they are redirected back to the dashboard page.
  expect(signInRes.status).toBe(303);
  expect(signInRes.headers.get('Location')).toBe('/dashboard/');
});

}); // end describe
