// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US17-selection-modes.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";

import { extractSessionCookie, get, getAuthForm, post, signInAs, submitAuthForm } from "./helpers";

import { selectReuse, selectPick, selectRatchet, selectList, createSelectionState } from "../src/domain/prestoplot/selectionModes.js";
import { trainMarkovChain, generateMarkov } from "../src/domain/prestoplot/markovChain.js";
import { Mulberry32 } from "../src/domain/galaxy/prng.js";

describe("US17-selection-modes", () => {

// REUSE mode selects with replacement.
// Source: specs/acceptance-specs/US17-selection-modes.txt:2
it("REUSE mode selects with replacement.", async () => {
  // GIVEN a rule with REUSE mode.
  const items = ["red", "blue", "green"];
  const prng = new Mulberry32(42);
  const rng = { next: (): number => prng.random() };

  // WHEN rendered multiple times from the same seed.
  const results: string[] = [];
  for (let i = 0; i < 20; i++) {
    results.push(selectReuse(items, rng));
  }

  // THEN items are selected with replacement allowing repeats.
  // With 20 draws from 3 items, repeats are virtually guaranteed.
  const unique = new Set(results);
  expect(unique.size).toBeLessThan(results.length);
  // All results must be valid items.
  for (const r of results) {
    expect(items).toContain(r);
  }
});

// PICK mode selects without replacement per epoch.
// Source: specs/acceptance-specs/US17-selection-modes.txt:9
it("PICK mode selects without replacement per epoch.", async () => {
  // GIVEN a rule with PICK mode.
  const items = ["red", "blue", "green"];
  const prng = new Mulberry32(42);
  const rng = { next: (): number => prng.random() };
  const state = createSelectionState();

  // WHEN rendered N times where N equals the item count.
  const epoch1: string[] = [];
  for (let i = 0; i < items.length; i++) {
    epoch1.push(selectPick(items, rng, "test", state));
  }

  // THEN each item appears exactly once before any repeats.
  const sorted = [...epoch1].sort();
  expect(sorted).toEqual(["blue", "green", "red"]);
});

// RATCHET mode cycles items sequentially.
// Source: specs/acceptance-specs/US17-selection-modes.txt:16
it("RATCHET mode cycles items sequentially.", async () => {
  // GIVEN a rule with RATCHET mode.
  const items = ["alpha", "beta", "gamma"];
  const state = createSelectionState();

  // WHEN rendered sequentially.
  const results: string[] = [];
  for (let i = 0; i < 6; i++) {
    results.push(selectRatchet(items, "test", state));
  }

  // THEN items cycle in order and wrap around after the last item.
  expect(results).toEqual(["alpha", "beta", "gamma", "alpha", "beta", "gamma"]);
});

// LIST mode returns item at specified index.
// Source: specs/acceptance-specs/US17-selection-modes.txt:23
it("LIST mode returns item at specified index.", async () => {
  // GIVEN a rule with LIST mode and an index.
  const items = ["first", "second", "third"];

  // WHEN rendered.
  // THEN the specific item at that index is returned.
  expect(selectList(items, 0)).toBe("first");
  expect(selectList(items, 1)).toBe("second");
  expect(selectList(items, 2)).toBe("third");
  // Clamping behavior.
  expect(selectList(items, -1)).toBe("first");
  expect(selectList(items, 99)).toBe("third");
});

// MARKOV mode generates novel strings from training data.
// Source: specs/acceptance-specs/US17-selection-modes.txt:30
it("MARKOV mode generates novel strings from training data.", async () => {
  // GIVEN a rule with MARKOV mode and training data.
  const corpus = ["alice", "alicia", "albert", "alfred", "alvin"];
  const trainResult = trainMarkovChain(corpus, 2);
  expect(trainResult.success).toBe(true);
  if (!trainResult.success) return;

  const prng = new Mulberry32(42);
  const rng = { next: (): number => prng.random() };

  // WHEN rendered.
  const genResult = generateMarkov(trainResult.value, rng);

  // THEN a novel string is generated using character-level Markov chain probabilities.
  expect(genResult.success).toBe(true);
  if (!genResult.success) return;
  expect(genResult.value.length).toBeGreaterThan(0);
  // The generated string should start with "al" since all training data starts that way.
  expect(genResult.value.startsWith("al")).toBe(true);
});

}); // end describe
