// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US19-grammar-parsing.txt

import { describe, it, expect } from "vitest";

import { parseGrammar } from "../src/application/prestoplot/grammarParser.js";
import { grammarToDto } from "../src/application/prestoplot/dto.js";
import { renderStory } from "../src/application/prestoplot/renderStoryService.js";
import { createInMemoryStorage } from "../src/infrastructure/prestoplot/inMemoryStorage.js";
import { createMulberry32Random } from "../src/infrastructure/prestoplot/mulberry32Random.js";
import { Jinja2Engine } from "../src/infrastructure/prestoplot/jinja2Engine.js";

describe("US19-grammar-parsing", () => {

// Valid grammar file produces correct Grammar object.
// Source: specs/acceptance-specs/US19-grammar-parsing.txt:2
it("Valid grammar file produces correct Grammar object.", async () => {
  // GIVEN a valid YAML grammar file with text list and struct rules.
  const yaml = [
    '"Begin": ["Hello", "Hi"]',
    '"character": {"name": "names", "class": "classes"}',
    '"names": ["Alice", "Bob"]',
    '"classes": ["Warrior", "Mage"]',
  ].join("\n");

  // WHEN parsed.
  const result = parseGrammar(yaml, "test-grammar");

  // THEN a Grammar object is produced with all rules correctly typed.
  expect(result.success).toBe(true);
  if (!result.success) return;

  const grammar = result.value;
  expect(grammar.key).toBe("test-grammar");

  const beginRule = grammar.rules.get("Begin");
  expect(beginRule).toBeDefined();
  expect(beginRule!.type).toBe("list");

  const characterRule = grammar.rules.get("character");
  expect(characterRule).toBeDefined();
  expect(characterRule!.type).toBe("struct");

  const namesRule = grammar.rules.get("names");
  expect(namesRule).toBeDefined();
  expect(namesRule!.type).toBe("list");
});

// Unknown rule type produces clear error.
// Source: specs/acceptance-specs/US19-grammar-parsing.txt:9
it("Unknown rule type produces clear error.", async () => {
  // GIVEN a YAML file with an unknown rule type.
  const yaml = '"Begin": true';

  // WHEN parsed.
  const result = parseGrammar(yaml, "bad-grammar");

  // THEN a clear error message identifies the invalid rule.
  expect(result.success).toBe(false);
  if (result.success) return;
  expect(result.error.code).toBe("unknown_rule_type");
});

// Missing rule reference produces validation error.
// Source: specs/acceptance-specs/US19-grammar-parsing.txt:16
it("Missing rule reference produces validation error.", async () => {
  // GIVEN a grammar where a struct field references a non-existent rule.
  // parseGrammar does not cross-validate struct field references;
  // renderStory's resolveIncludes does. Store and render to trigger.
  const yaml = '"Begin": {"name": "nonexistent"}';
  const parseResult = parseGrammar(yaml, "missing-ref");
  expect(parseResult.success).toBe(true);
  if (!parseResult.success) return;

  const storage = createInMemoryStorage();
  await storage.save("missing-ref", grammarToDto(parseResult.value));

  // WHEN rendered.
  const renderResult = await renderStory(
    { grammarKey: "missing-ref", seed: "test" },
    storage,
    createMulberry32Random(),
    new Jinja2Engine(),
  );

  // THEN a validation error reports the missing reference.
  expect(renderResult.success).toBe(false);
  if (renderResult.success) return;
  expect(renderResult.kind).toBe("parse_error");
  expect(renderResult).toHaveProperty("message");
  expect((renderResult as { message: string }).message).toContain("nonexistent");
});

// Circular includes are detected at parse time.
// Source: specs/acceptance-specs/US19-grammar-parsing.txt:23
it("Circular includes are detected at parse time.", async () => {
  // GIVEN two grammars that include each other.
  const yamlA = [
    '"include": ["grammar-b"]',
    '"Begin": ["from A"]',
  ].join("\n");
  const yamlB = [
    '"include": ["grammar-a"]',
    '"Begin": ["from B"]',
  ].join("\n");

  const parseA = parseGrammar(yamlA, "grammar-a");
  const parseB = parseGrammar(yamlB, "grammar-b");
  expect(parseA.success).toBe(true);
  expect(parseB.success).toBe(true);
  if (!parseA.success || !parseB.success) return;

  const storage = createInMemoryStorage();
  await storage.save("grammar-a", grammarToDto(parseA.value));
  await storage.save("grammar-b", grammarToDto(parseB.value));

  // WHEN rendered (resolveIncludes detects cycles).
  const result = await renderStory(
    { grammarKey: "grammar-a", seed: "test" },
    storage,
    createMulberry32Random(),
    new Jinja2Engine(),
  );

  // THEN a circular dependency error is raised.
  expect(result.success).toBe(false);
  if (result.success) return;
  expect(result.kind).toBe("circular_include");
});

}); // end describe
