// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US21-article-generation.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";

import { extractSessionCookie, get, getAuthForm, post, signInAs, submitAuthForm } from "./helpers";
import { getArticle } from "../src/domain/prestoplot/articleGeneration.js";

describe("US21-article-generation", () => {

// Vowel-starting word gets "an" article.
// Source: specs/acceptance-specs/US21-article-generation.txt:2
it("Vowel-starting word gets \"an\" article.", () => {
  // GIVEN the word "apple".
  const word = "apple";

  // WHEN an indefinite article is generated.
  const article = getArticle(word);

  // THEN the result is "an apple".
  expect(article).toBe("an");
  expect(`${article} ${word}`).toBe("an apple");
});

// Consonant-sound word gets "a" article despite vowel spelling.
// Source: specs/acceptance-specs/US21-article-generation.txt:9
it("Consonant-sound word gets \"a\" article despite vowel spelling.", () => {
  // GIVEN the word "university".
  const word = "university";

  // WHEN an indefinite article is generated.
  const article = getArticle(word);

  // THEN the result is "a university".
  expect(article).toBe("a");
  expect(`${article} ${word}`).toBe("a university");
});

// Silent-h word gets "an" article.
// Source: specs/acceptance-specs/US21-article-generation.txt:16
it("Silent-h word gets \"an\" article.", () => {
  // GIVEN the word "hour".
  const word = "hour";

  // WHEN an indefinite article is generated.
  const article = getArticle(word);

  // THEN the result is "an hour".
  expect(article).toBe("an");
  expect(`${article} ${word}`).toBe("an hour");
});

// European-sound word gets "a" article despite vowel start.
// Source: specs/acceptance-specs/US21-article-generation.txt:23
it("European-sound word gets \"a\" article despite vowel start.", () => {
  // GIVEN the word "European".
  const word = "European";

  // WHEN an indefinite article is generated.
  const article = getArticle(word);

  // THEN the result is "a European".
  expect(article).toBe("a");
  expect(`${article} ${word}`).toBe("a European");
});

}); // end describe
