// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US23-grammar-includes.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";

import { extractSessionCookie, get, getAuthForm, post, signInAs, submitAuthForm } from "./helpers";

describe("US23-grammar-includes", () => {

// Included grammar rules are available for reference.
// Source: specs/acceptance-specs/US23-grammar-includes.txt:2
it("Included grammar rules are available for reference.", async () => {
  // GIVEN grammar A that includes grammar B.
  // WHEN grammar A is rendered.
  // THEN rules from grammar B are available for reference.

  throw new Error("acceptance test not yet bound");
});

// Circular includes are detected and rejected.
// Source: specs/acceptance-specs/US23-grammar-includes.txt:9
it("Circular includes are detected and rejected.", async () => {
  // GIVEN grammar A includes B and B includes A.
  // WHEN parsing.
  // THEN a circular include error is raised.

  throw new Error("acceptance test not yet bound");
});

// Transitive includes resolve across multiple grammars.
// Source: specs/acceptance-specs/US23-grammar-includes.txt:16
it("Transitive includes resolve across multiple grammars.", async () => {
  // GIVEN grammar A includes B which includes C.
  // WHEN rendered.
  // THEN rules from all three grammars are available.

  throw new Error("acceptance test not yet bound");
});

}); // end describe
