// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.
// Source: specs/acceptance-specs/US23-grammar-includes.txt

import { SELF } from "cloudflare:test";
import { describe, it, expect } from "vitest";

import { extractSessionCookie, get, getAuthForm, post, signInAs, submitAuthForm } from "./helpers";

import { parseGrammar } from "../src/application/prestoplot/grammarParser.js";
import { grammarToDto } from "../src/application/prestoplot/dto.js";
import { renderStory } from "../src/application/prestoplot/renderStoryService.js";
import { createInMemoryStorage } from "../src/infrastructure/prestoplot/inMemoryStorage.js";
import { createMulberry32Random } from "../src/infrastructure/prestoplot/mulberry32Random.js";
import { Jinja2Engine } from "../src/infrastructure/prestoplot/jinja2Engine.js";

describe("US23-grammar-includes", () => {

// Included grammar rules are available for reference.
// Source: specs/acceptance-specs/US23-grammar-includes.txt:2
it("Included grammar rules are available for reference.", async () => {
  // GIVEN grammar A that includes grammar B.
  const storage = createInMemoryStorage();
  const random = createMulberry32Random();
  const engine = new Jinja2Engine();

  const yamlB = [
    '"Begin": "placeholder"',
    '"animal":',
    '  - "fox"',
  ].join("\n");
  const parsedB = parseGrammar(yamlB, "grammar-b");
  expect(parsedB.success).toBe(true);
  if (!parsedB.success) return;
  await storage.save("grammar-b", grammarToDto(parsedB.value));

  const yamlA = [
    '"include":',
    '  - "grammar-b"',
    '"Begin": "The {{animal}} runs"',
  ].join("\n");
  const parsedA = parseGrammar(yamlA, "grammar-a");
  expect(parsedA.success).toBe(true);
  if (!parsedA.success) return;
  await storage.save("grammar-a", grammarToDto(parsedA.value));

  // WHEN grammar A is rendered.
  const result = await renderStory({ grammarKey: "grammar-a", seed: "alpha" }, storage, random, engine);

  // THEN rules from grammar B are available for reference.
  expect(result.success).toBe(true);
  if (!result.success) return;
  expect(result.text).toBe("The fox runs");
});

// Circular includes are detected and rejected.
// Source: specs/acceptance-specs/US23-grammar-includes.txt:9
it("Circular includes are detected and rejected.", async () => {
  // GIVEN grammar A includes B and B includes A.
  const storage = createInMemoryStorage();
  const random = createMulberry32Random();
  const engine = new Jinja2Engine();

  const yamlA = [
    '"include":',
    '  - "grammar-b"',
    '"Begin":',
    '  - "Hello"',
  ].join("\n");
  const parsedA = parseGrammar(yamlA, "grammar-a");
  expect(parsedA.success).toBe(true);
  if (!parsedA.success) return;
  await storage.save("grammar-a", grammarToDto(parsedA.value));

  const yamlB = [
    '"include":',
    '  - "grammar-a"',
    '"Begin":',
    '  - "Goodbye"',
  ].join("\n");
  const parsedB = parseGrammar(yamlB, "grammar-b");
  expect(parsedB.success).toBe(true);
  if (!parsedB.success) return;
  await storage.save("grammar-b", grammarToDto(parsedB.value));

  // WHEN parsing.
  const result = await renderStory({ grammarKey: "grammar-a", seed: "alpha" }, storage, random, engine);

  // THEN a circular include error is raised.
  expect(result.success).toBe(false);
  if (result.success) return;
  expect(result.kind).toBe("circular_include");
});

// Transitive includes resolve across multiple grammars.
// Source: specs/acceptance-specs/US23-grammar-includes.txt:16
it("Transitive includes resolve across multiple grammars.", async () => {
  // GIVEN grammar A includes B which includes C.
  const storage = createInMemoryStorage();
  const random = createMulberry32Random();
  const engine = new Jinja2Engine();

  const yamlC = [
    '"Begin": "placeholder"',
    '"color":',
    '  - "red"',
  ].join("\n");
  const parsedC = parseGrammar(yamlC, "grammar-c");
  expect(parsedC.success).toBe(true);
  if (!parsedC.success) return;
  await storage.save("grammar-c", grammarToDto(parsedC.value));

  const yamlB = [
    '"include":',
    '  - "grammar-c"',
    '"Begin": "placeholder"',
    '"animal":',
    '  - "fox"',
  ].join("\n");
  const parsedB = parseGrammar(yamlB, "grammar-b");
  expect(parsedB.success).toBe(true);
  if (!parsedB.success) return;
  await storage.save("grammar-b", grammarToDto(parsedB.value));

  const yamlA = [
    '"include":',
    '  - "grammar-b"',
    '"Begin": "The {{color}} {{animal}}"',
  ].join("\n");
  const parsedA = parseGrammar(yamlA, "grammar-a");
  expect(parsedA.success).toBe(true);
  if (!parsedA.success) return;
  await storage.save("grammar-a", grammarToDto(parsedA.value));

  // WHEN rendered.
  const result = await renderStory({ grammarKey: "grammar-a", seed: "alpha" }, storage, random, engine);

  // THEN rules from all three grammars are available.
  expect(result.success).toBe(true);
  if (!result.success) return;
  expect(result.text).toBe("The red fox");
});

}); // end describe
