import { writeFile } from 'fs/promises';
import { basename, extname } from 'path';

import type { Feature } from './types.js';

/**
 * Sentinel string placed in generated stub it() blocks.
 * If a block contains this string, it has not yet been bound to a real
 * implementation and will be regenerated on the next pipeline run.
 */
export const UnboundSentinel = 'throw new Error("acceptance test not yet bound")';

/**
 * Scans the source text of a generated test file and extracts all it() blocks
 * that have been bound to real implementations (i.e. do NOT contain the
 * UnboundSentinel). Unbound stubs are skipped.
 *
 * Only top-level it() calls (no leading whitespace) are recognised.
 *
 * The brace counter handles basic string literal detection to avoid counting
 * braces inside strings. Template literals (backtick strings) are tracked as
 * opaque strings: braces inside `${}` expressions within a template literal
 * are not counted correctly if those expressions contain nested string literals
 * (e.g. `` `value: ${"a" + "b"}` ``). This is a known limitation. Generated
 * test files do not produce this pattern in practice.
 *
 * @param source - The full text of the existing generated test file.
 * @returns A Map from test description to the full it() block text.
 */
export function extractBoundFunctions(source: string): Map<string, string> {
  const result = new Map<string, string>();
  const lines = source.split('\n');
  let i = 0;

  while (i < lines.length) {
    /* c8 ignore next */
    const line = lines[i] ?? '';
    const match =
      /^it\("((?:[^"\\]|\\.)+)", async \(\) => \{/.exec(line) ??
      /^it\('((?:[^'\\]|\\.)+)', async \(\) => \{/.exec(line);

    if (match !== null) {
      /* c8 ignore next */
      const description = (match[1] ?? '').replace(/\\(.)/g, '$1');
      const startLine = i;
      let depth = 0;
      let endLine = -1;
      let inString: string | null = null;

      outer: for (let j = startLine; j < lines.length; j++) {
        /* c8 ignore next */
        const scanLine = lines[j] ?? '';
        for (let k = 0; k < scanLine.length; k++) {
          /* c8 ignore next */
          const ch = scanLine[k] ?? '';
          const next = scanLine[k + 1];

          if (inString !== null) {
            if (ch === '\\') {
              k++; // skip escaped char
            } else if (ch === inString) {
              inString = null;
            }
          } else if (ch === '"' || ch === "'" || ch === '`') {
            inString = ch;
          } else if (ch === '/' && next === '/') {
            break; // rest of line is a comment
          } else if (ch === '{') {
            depth++;
          } else if (ch === '}') {
            depth--;
            if (depth === 0) {
              endLine = j;
              break outer;
            }
          }
        }
      }

      if (endLine >= 0) {
        const block = lines.slice(startLine, endLine + 1).join('\n');
        if (!block.includes(UnboundSentinel)) {
          result.set(description, block);
        }
        i = endLine + 1;
        continue;
      }
    }

    i++;
  }

  return result;
}

/**
 * Converts a string to a safe JavaScript identifier by replacing
 * non-alphanumeric sequences with underscores and lowercasing.
 *
 * @param desc - The string to sanitize.
 * @returns A safe lowercase identifier string.
 */
export function sanitizeFuncName(desc: string): string {
  return desc
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase();
}

/**
 * Generates the content of a Vitest test file from a Feature IR.
 *
 * Bound implementations (it() blocks not containing the UnboundSentinel) are
 * preserved verbatim from the existing source. Unbound stubs are regenerated
 * from the current scenario list. Orphaned bound functions (those whose
 * description no longer matches any scenario) are appended with a warning
 * comment.
 *
 * @param feature - The parsed Feature IR.
 * @param existingSource - The current content of the test file (empty string if the file does not yet exist).
 * @returns The full content of the generated test file.
 */
export function generateTests(feature: Feature, existingSource: string): string {
  const boundFunctions = extractBoundFunctions(existingSource);
  const specName = basename(feature.sourceFile, extname(feature.sourceFile));

  const lines: string[] = [];

  // Header
  lines.push(
    '// Code generated by acceptance-pipeline. Stubs are regenerated; bound implementations are preserved.'
  );
  lines.push(`// Source: ${feature.sourceFile.replace(/[\r\n]/g, '')}`);
  lines.push('');

  // Imports
  lines.push('import { SELF } from "cloudflare:test";');
  lines.push('import { describe, it, expect } from "vitest";');
  lines.push('');

  // Describe block opening
  lines.push(`describe("${specName.replace(/"/g, '\\"')}", () => {`);
  lines.push('');

  const emittedDescriptions = new Set<string>();

  for (const scenario of feature.scenarios) {
    const { description, line, steps } = scenario;

    // Scenario comment header
    lines.push(`// ${description.replace(/[\r\n]/g, '')}`);
    lines.push(`// Source: ${feature.sourceFile.replace(/[\r\n]/g, '')}:${line}`);

    const boundBlock = boundFunctions.get(description);
    if (boundBlock !== undefined) {
      // Preserved bound implementation
      lines.push(boundBlock);
    } else {
      // Generate stub
      const stepComments = steps.map(
        (s) => `  // ${s.keyword.replace(/[\r\n]/g, '')} ${s.text.replace(/[\r\n]/g, '')}`
      );
      lines.push(`it("${description.replace(/"/g, '\\"')}", async () => {`);
      for (const comment of stepComments) {
        lines.push(comment);
      }
      lines.push('');
      lines.push(`  ${UnboundSentinel};`);
      lines.push('});');
    }

    lines.push('');
    emittedDescriptions.add(description);
  }

  // Emit orphaned bound functions
  for (const [desc, block] of boundFunctions) {
    if (!emittedDescriptions.has(desc)) {
      lines.push('// WARNING: orphaned bound function');
      lines.push(block);
      lines.push('');
    }
  }

  lines.push('}); // end describe');

  return lines.join('\n') + '\n';
}

/* c8 ignore start */
/**
 * Writes the generated test file content to disk.
 *
 * This function is the I/O boundary for the generator and is exempt from
 * coverage requirements.
 *
 * @param path - The file path to write.
 * @param content - The content to write.
 */
export async function writeTestFileImpl(path: string, content: string): Promise<void> {
  await writeFile(path, content, 'utf-8');
}
/* c8 ignore stop */
