/**
 * CLI entry point for the galaxy seeder tool.
 *
 * Seeds a D1 database with galaxy data generated by the galaxy-generator.
 * Orchestrates: read → validate → build graph → compute BTN → write SQL.
 *
 * Exit codes:
 * - 0: Success
 * - 1: Invalid arguments, read failure, validation failure, or write failure
 *
 * @module index
 */

import { writeFile } from 'node:fs/promises';

import type { Route, StarSystem } from '../../../src/domain/galaxy/types.js';

import { computeBtn } from './btn.js';
import { buildAdjacencyList, discoverPairs } from './graph.js';
import { readMetadata, readRoutes, readSystems } from './reader.js';
import type { TradePairRow } from './sql-writer.js';
import { generateSQL } from './sql-writer.js';
import { validateInput } from './validator.js';

/** Parsed CLI arguments for the galaxy seeder. */
interface SeederArgs {
  /** Path to the galaxy-generator output directory. */
  input: string;
  /** Path to the output SQL file. When omitted, SQL is written to stdout. */
  output?: string;
}

/** Successful parse result. */
interface ParseArgsSuccess {
  /** Indicates a successful parse. */
  readonly ok: true;
  /** Parsed CLI arguments. */
  readonly args: SeederArgs;
  /** Whether verbose output is enabled. */
  readonly verbose: boolean;
}

/** Failed parse result. */
interface ParseArgsFailure {
  /** Indicates a failed parse. */
  readonly ok: false;
  /** Human-readable error message. */
  readonly error: string;
}

/** Result of parsing CLI arguments — discriminated union. */
type ParseArgsResult = ParseArgsSuccess | ParseArgsFailure;

/** All known CLI flags that accept a value argument. */
const VALUE_FLAGS = new Set(['--input', '--output']);

/**
 * Extracts a human-readable message from an unknown error value.
 *
 * @param error - the caught error value
 * @returns string representation of the error
 */
function extractErrorMessage(error: unknown): string {
  if (error instanceof Error) {
    return error.message;
  }
  return String(error);
}

/**
 * Parses command-line arguments into structured data.
 *
 * @param argv - raw command-line arguments (without node and script path)
 * @returns parsed arguments or error
 */
export function parseArgs(argv: readonly string[]): ParseArgsResult {
  let input: string | undefined;
  let output: string | undefined;
  let verbose = false;

  let i = 0;
  while (i < argv.length) {
    const flag = argv[i]!;

    if (flag === '--verbose') {
      verbose = true;
      i++;
      continue;
    }

    if (VALUE_FLAGS.has(flag)) {
      const value = argv[i + 1];
      if (value === undefined || value.startsWith('--')) {
        return { ok: false, error: `${flag} requires a value` };
      }

      if (flag === '--input') {
        input = value;
      } else {
        output = value;
      }

      i += 2;
      continue;
    }

    return { ok: false, error: `Unknown argument: ${flag}` };
  }

  if (input === undefined) {
    return { ok: false, error: 'Missing required --input argument' };
  }

  return { ok: true, args: { input, ...(output !== undefined ? { output } : {}) }, verbose };
}

/**
 * Logs a verbose progress message to stderr.
 *
 * @param verbose - whether verbose mode is enabled
 * @param message - the message to log
 */
function log(verbose: boolean, message: string): void {
  if (verbose) {
    process.stderr.write(`${message}\n`);
  }
}

/**
 * Main CLI entry point for the galaxy seeder.
 *
 * Orchestrates the full pipeline: parse args → read files → validate →
 * build graph → compute BTN → generate SQL → write output.
 *
 * @param argv - raw command-line arguments (without node and script path)
 * @returns exit code (0 for success, 1 for failure)
 */
export async function main(argv: readonly string[]): Promise<number> {
  const parsed = parseArgs(argv);
  if (!parsed.ok) {
    process.stderr.write(`Error: ${parsed.error}\n`);
    return 1;
  }

  const { input, output } = parsed.args;
  const { verbose } = parsed;

  // ─── Read ───────────────────────────────────────────────────────────────────
  let metadata: unknown;
  let systemsRaw: unknown[];
  let routesRaw: unknown;

  log(verbose, 'Reading galaxy data...');
  try {
    [metadata, systemsRaw, routesRaw] = await Promise.all([
      readMetadata(input),
      readSystems(input),
      readRoutes(input),
    ]);
  } catch (error: unknown) {
    process.stderr.write(`Error: ${extractErrorMessage(error)}\n`);
    return 1;
  }

  // ─── Validate ───────────────────────────────────────────────────────────────
  log(verbose, 'Validating input...');
  const validation = validateInput({ metadata, systems: systemsRaw, routes: routesRaw });
  if (!validation.ok) {
    process.stderr.write(
      `Validation errors:\n${validation.errors.map((e) => `  - ${e}`).join('\n')}\n`
    );
    return 1;
  }

  // ─── Cast validated data ────────────────────────────────────────────────────
  const systems = systemsRaw as StarSystem[];
  const routesObj = routesRaw as { routes: Route[] };
  const routes = routesObj.routes;

  // ─── Build graph + discover pairs ───────────────────────────────────────────
  log(verbose, 'Building route graph...');
  const adj = buildAdjacencyList(routes);
  const pairs = discoverPairs(adj);

  // ─── Compute BTN ────────────────────────────────────────────────────────────
  log(verbose, 'Computing trade numbers...');
  const systemMap = new Map<string, StarSystem>();
  for (const sys of systems) {
    systemMap.set(sys.id, sys);
  }

  const tradePairs: TradePairRow[] = [];
  for (const pair of pairs) {
    const sysA = systemMap.get(pair.systemA);
    const sysB = systemMap.get(pair.systemB);
    if (sysA !== undefined && sysB !== undefined) {
      const btn = computeBtn(
        sysA.economics.worldTradeNumber,
        sysB.economics.worldTradeNumber,
        pair.hops
      );
      tradePairs.push({ systemAId: pair.systemA, systemBId: pair.systemB, btn, hops: pair.hops });
    }
  }

  // ─── Generate SQL ───────────────────────────────────────────────────────────
  log(verbose, 'Generating SQL...');
  const sql = generateSQL(systems, routes, tradePairs);

  // ─── Write output ───────────────────────────────────────────────────────────
  try {
    if (output !== undefined) {
      log(verbose, `Writing SQL to ${output}...`);
      await writeFile(output, sql, 'utf-8');
    } else {
      process.stdout.write(sql);
    }
  } catch (error: unknown) {
    process.stderr.write(`Error: ${extractErrorMessage(error)}\n`);
    return 1;
  }

  return 0;
}
